src/Entity/Theme.php
<?php

namespace App\Entity;

use App\Repository\ThemeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ThemeRepository::class)]
class Theme
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\OneToMany(mappedBy: 'theme', targetEntity: 'App\Entity\Discussion')]
    private $discussions;

    public function __construct()
    {
        $this->discussions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * @param mixed $titre
     */
    public function setTitre($titre): void
    {
        $this->titre = $titre;
    }

    public function getDiscussions(): Collection
    {
        return $this->discussions;
    }

    public function getLastDiscussionDate(): ?\DateTimeInterface
    {
        $discussions = $this->getDiscussions();
        if ($discussions->isEmpty()) {
            return null;
        }

        $lastDiscussion = $discussions->last();

        return $lastDiscussion->getCreatedAt();
    }


    public function getDiscussionCount(): int
    {
        return count($this->discussions);
    }


}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Theme;
use App\Form\ThemeType;
use App\Repository\ThemeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class HomeController extends AbstractController{
    #[Route('/', name: 'app_home')]
    public function index(Request $request, ThemeRepository $themeRepository, EntityManagerInterface $em): Response
    {

        $page = $request->query->getInt('page', 1);


        $themes = $themeRepository->findThemesPaginated($page);

        $theme = new Theme();
        $form = $this->createForm(ThemeType::class, $theme);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em->persist($theme);
            $em->flush();

            $this->addFlash('success', 'Le theme a été créer!');

            return $this->redirectToRoute('app_home');
        }

        return $this->render('home/index.html.twig', [
            'themes' => $themes,
            'current_page' => $page,
            'total_pages' => ceil(count($themes) / 5),
            'form' => $form->createView(),
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <h1 class="title_home">Bienvenue sur mon Forum</h1>
    </div>

    <h1>Liste des thèmes</h1>

    <table>
        <thead>
        <tr>
            <th>Titre</th>
            <th>Dernière discussion</th>
            <th>Nombre de discussions</th>
        </tr>
        </thead>
        <tbody>
        {% for theme in themes %}
            <tr>
                <td><a href="{{ path('app_theme', {'id': theme.id}) }}">{{ theme.titre }}</a></td>
                <td>
                    {% if theme.lastDiscussionDate %}
                        {{ theme.lastDiscussionDate|date('d/m/Y H:i') }}
                    {% else %}
                        Aucune discussion
                    {% endif %}
                </td>
                <td>{{ theme.discussionCount }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <br>
    {% if current_page > 1 %}
        <a href="?page={{ current_page - 1 }}">Page précédente</a>
    {% endif %}

    <span>Page {{ current_page }} sur {{ total_pages }}</span>

    {% if current_page < total_pages %}
        <a href="?page={{ current_page + 1 }}">Page suivante</a>
    {% endif %}

    <br><br><br><br><br>

    {% if app.session.get('user')  %}

        {% if 'ROLE_MODERATOR' in app.session.get('user')['roles'] %}
            <h2>Créer un nouveaux theme (Moderateur)</h2>
            {{ form(form) }}
        {% endif %}

    {% endif %}

{% endblock %}